[package]
name = "_blockchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.163"
serde_derive = "1.0.163"
serde_json = "1.0.96"
sha2 = "0.10.6"
time = "0.3.21"
