[package]
name = "_snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.128.0"
rand = "0.8.5"


[target.x86_64-unknown-linux-musl]
linker = "rust-lld"
